version: '3.8'

services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile-master
    restart: unless-stopped
    hostname: jenkins-master
    container_name: jenkins-master
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    volumes:
      - ./jenkins:/var/jenkins_home
      - ./jenkins/aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - npm-network
      - default

  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile-agent      
    restart: unless-stopped
    hostname: jenkins-agent
    container_name: jenkins-agent
    user: root
    depends_on:
      - jenkins-master
    environment:
      - JENKINS_URL=http://${JENKINS_MASTER_HOST}:${JENKINS_MASTER_PORT}
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME}
      - JENKINS_SECRET=${JENKINS_SECRET}        
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_WEB_SOCKET=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-agent:/home/jenkins/agent
    networks:
      - npm-network

networks:
  npm-network:
    name: npm-network
    external: true
