apiVersion: v1
kind: Namespace
metadata:
  name: jenkong
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkong-sa
  namespace: jenkong
secrets:
- name: jenkong-sa-token
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkong-sa-token
  namespace: jenkong
  annotations:
    kubernetes.io/service-account.name: jenkong-sa  
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkong-clusterrole
rules:
- apiGroups:
  - '*'
  resources:
  - deployments
  - pods
  - pods/log
  - events
  - services
  - pods/exec
  - horizontalpodautoscalers
  verbs:
  - get
  - watch
  - list
  - update
  - create
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkong-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkong-clusterrole
subjects:
  - kind: ServiceAccount
    name: jenkong-sa
    namespace: jenkong
